name: 1-build-pr-workflow

on:
  pull_request:
    branches:
      - main
    types: [closed, opened, synchronize]
  push:
    branches:
      - '*'

jobs:
  get-filenames:
    runs-on: ubuntu-latest
    outputs:
      set: ${{ steps.getLambdas.outputs.set }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get functions filenames
        id: getLambdas
        run: |
          lambdas=$(find apps -type f -name "*.py" -exec dirname {} \; | sed 's,^apps/,,')
          echo "::set-output name=matrix::${lambdas}"

  update-code:
    permissions:
      actions: write
      contents: write
      id-token: write
    needs: get-filenames
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: us-east-1

      - name: Verify Assumed Role
        run: aws sts get-caller-identity

      - name: Set Timestamp for Tag
        id: set-timestamp
        run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Running CHMOD to deploy script
        run: |
          chmod +x ./build.sh
  
      - name: Deploy Lambda Functions
        run: |
          bash ./build.sh ${{ env.TIMESTAMP }}

                    