name: Update Function Code
 
on:
  pull_request:
      branches:
      - main
      types: [opened, synchronize]
  push:
      branches:
      - '*'
jobs:
  get-filenames:
    runs-on: ubuntu-latest
    outputs:
      lambdaArray: ${{ steps.getLambdas.outputs.lambdas }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get functions filenames
        id: getLambdas
        run: |
          lambdas=$(ls -d apps/*/ | sed 's/\/$//')

  update-code:
    needs: get-filenames
    strategy:
      matrix:
        lambda: ${{ needs.get-filenames.outputs.lambdaArray }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: us-east-1

      # - name: Get AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: $ {{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2
      - name: List variables
        run: echo ${{matrix.lambda}}
      # - name: Zip Lambda functions
      #   run: zip -j ${{matrix.lambda}}.zip ./apps/${{matrix.lambda}}
      - name: Update Lambdas code
        run: echo ${{matrix.lambda}} --zip-file=fileb://${{matrix.lambda}}.zip
