name: Update Function Code

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  push:
    branches:
      - '*'

jobs:
  get-filenames:
    runs-on: ubuntu-latest
    outputs:
      # Corrected syntax for matrix output
      set: ${{ steps.getLambdas.outputs.set }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get functions filenames
        id: getLambdas
        run: |
          lambdas=$(ls -d apps/*/ | sed 's/\/$//')
          # Corrected syntax for setting matrix output
          echo "::set-output name=set::${lambdas}"

  update-code:
    needs: get-filenames
    strategy:
      matrix:
        # Use the matrix directly without needing outputs
        lambda: ${{fromJson(needs.get-filenames.outputs.set)}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: us-east-1

      - name: List variables
        run: echo ${{ matrix.lambda }}
      - name: Update Lambdas code
        run: echo ${{ matrix.lambda }} --zip-file=fileb://${{ matrix.lambda }}.zip
